### ISSUE TITLE
Add task to promote NuGet packages to views

### ISSUE THREAD

**Issue by sumo300** [Microsoft/vsts-tasks#4592]
Add a task to the set of NuGet tasks to promote packages to a particular view when publishing to internal package management (or extend package publisher to include option to promote).

**Comment by alexmullans** [comment]
Thanks for this feature request. I'm closing it here as not a bug. Please feel free to add it as a feature request on the [Package Management UserVoice](https://visualstudio.uservoice.com/forums/330519-team-services/category/145266-package-management), or consider using [this 3rd-party task from the Marketplace](https://marketplace.visualstudio.com/items?itemName=rvo.vsts-promotepackage-task).

**Comment by sumo300** [comment]
Thanks!  Added.
https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/19690240-add-task-to-promote-packages-for-release-managemen

**Comment by Misiu** [comment]
https://developercommunity.visualstudio.com/idea/365674/add-task-to-promote-packages-for-release-managemen.html

This still isn't available.
The only thing missing is `view` property in nuget push:

```
- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Utils'
    vstsView: 'Release' #this option is missing
    versioningScheme: 'off'
    allowPackageConflicts: true
```
Any updates or workarounds?
