### ISSUE TITLE
Dot Net Core Wild Card Paths Ignore

### ISSUE THREAD

**Issue by JacobAtchley** [Microsoft/vsts-tasks#4712]
I recently upgraded a VSTS task group from `0.*` to `1.*` for dot net core restore, build, test, and publish tasks. My repository has a mix of dotnet core and dotnet 4.6 projects. previously i could exclude the 4.6 projects with the slug `**/*.csproj;-:**/My46Project.csproj`.

When upgrading to the `1.*` build task the dot net core task fail to find my `.csproj` files and my build fails. 

Any suggestions on how I can exclude the "legacy" 4.6 project while still using the upgraded VSTS tasks?

**Comment by ds-249** [comment]
@JacobAtchley the delimiter for different patterns is a newline now.
And use '!' for exclusion instead of -:
So your new regex should be 
"`**/*.csproj`
 `!**/My46Project.csproj`"

**Comment by ds-ms** [comment]
Why have you assigned again?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hiyadav** [comment]
Hi,
You can give Excluding patterns in this format: 
pattern1
!excludepatter1

The changes being:
1. new line will work as Pattern seperator unlike earlier where ";" was used.
2. Exclude patterns need to start with "!" rather than "-:"

**Comment by JacobAtchley** [comment]
@ds-249 Thanks for the info. Is this documented anywhere?

**Comment by ds-249** [comment]
[Here is a link](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/findingfiles.md) to the documentation of the library used underneath for the finding files based on patterns.

**Comment by dasiths** [comment]
@hiyadav any idea of how to do it in a yaml build file?

```
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: '**/*.csproj !**/Net4.6ProjectToExclude.csproj'
      arguments: '--configuration $(BuildConfiguration)'
```

**Comment by scottluskcis** [comment]
I have the same question as @dasiths, how do you accomplish this with yaml? I've tried using newline separation in the yaml, even tried using the \n character and a -: or ; as well but no luck.

**Comment by dasiths** [comment]
I think this worked for me
```
projects: |
                 '**/*.csproj'
                 '**/*.Tests.csproj'
```

**Comment by irontoby** [comment]
I had to omit the single quotes in order to use variable substitution, e.g:

```yaml
variables:
  basedir: 'MyCorp.MyProject/**'
  buildProjects: |
    $(basedir)/*.csproj
    !$(basedir)/*.SkipMe.csproj

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '$(buildProjects)'
```

**Comment by lipalath-ms** [comment]
Could someone please let me know how I could exclude projects Repositories.* and Entities from below task? This is what I tried:

```
- task: DotNetCoreCLI@2
          displayName: 'dotnet test'
          inputs:
            command: test
            projects: 'Services.Tests'
            arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)\Coverage\ /p:Exclude="[Repositories.*]*" /p:Exclude="[Entities]*"'
```
