### ISSUE TITLE
How to publish the code coverage result with a .coverage file? 

### ISSUE THREAD

**Issue by chunliu** [Microsoft/vsts-tasks#5562]
I am working on a .net core 2.0 project. With the latest version of Visual Studio agent, I can collect the code coverage with a command like below: 

`"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" /framework:".NETCoreApp,Version=v1.1" /collect:"Code Coverage" "G:\tmp\trial\bin\Debug\netcoreapp1.1\trial.dll`

The command generates a .coverage file which can be opened in Visual Studio. But how can I publish the result in vsts? It seems the Publish Code Coverage task of vsts doesn't understand this file.

**Comment by pjquirk** [comment]
The Publish Code Coverage task only supports [Cobertura](http://cobertura.github.io/cobertura/) and [JaCoCo](http://www.eclemma.org/jacoco/) output.

See [this thread and comment](https://github.com/Microsoft/vsts-tasks/issues/5066#issuecomment-329745668) for details on using the Visual Studio Test task to generate and publish the code coverage.

**Comment by chunliu** [comment]
@pjquirk I managed to get it work by following the thread you mentioned. Thanks.

**Comment by aashish2384** [comment]
I have generated .coverage file using vstest.console.exe and also I have exported the xml file by opening and exporting .coverage file. The final exported file contains .coveragexml extension, and this is xml file basically which has all the details of the tests and coverage report with source code linkgae.

How can I consume these files(.coverage, .coveragexml) in JACOCO plugin on Jenkins so that I can show the source code to users which got covered by unit tests.

I have tried EMMA plugin on generated .coveragexml file but it doesn't display source code, it just displays the overall result of failed/passed test cases.

**Comment by abhishkk** [comment]
@aashish2384 Can you please create a separate issue for this for better tracking?

**Comment by joshmouch** [comment]
@pjquirk Maybe I'm blind, but I don't see anywhere in that thread where it says how to convert a *.coverage file to a JaCoCo file (as required by VSTS).  Could you explain it here?

**Comment by joshmouch** [comment]
@aashish2384 Are you converting the .coverage to a .coveragexml within the DevOps pipeline? How are you doing this?

**Comment by pjquirk** [comment]
@joshmouch If you're already generating a .coverage file via VSTest, you just need to use the _Visual Studio Test_ task to run your tests and publish the coverage (by checking the "Code Coverage Enabled" box).  The _Publish Code Coverage_ task is really only for third party coverage files.

**Comment by joshmouch** [comment]
I've responded to this on another thread but, pasting here for searchability:

If that's true then the code coverage screen is pretty limited, correct?  This is what Resharper tells me is covered:

![image](https://user-images.githubusercontent.com/3098820/55234598-e2801300-5201-11e9-8ab0-40b5cf8a837b.png)

And this is all I see on the DevOps screen.  First, the 50% is wrong...

![image](https://user-images.githubusercontent.com/3098820/55234927-97b2cb00-5202-11e9-90f8-0745be74c2b6.png)

... then when I click on the "Code Coverage succeeded" header, it takes me to the "Code Coverage" tab, which only has a download link and no useful reports.

![image](https://user-images.githubusercontent.com/3098820/55234692-14917500-5202-11e9-8005-e279c81a2365.png)

I think I've come to the conclusion that the push here is to use a third party tool for the code coverage results.  I've also run across a nuget package called Coverlet which is supposed to convert ".coverage" binary files to xml, so I'll give that a go.

**Comment by Frankwayne** [comment]
for those still using old version of TFS.  I found the Task "Publish Test Results"  will publish the .trx files and if you go to advance  and select upload Test Attachments,  it will  also upload your code coverage files.  

You may need to do some additional work on excluding  test  .dll and various other dll with your runsettings file.    TFS should automagiclly  combine the .coverage files as well.

**Comment by granadacoder** [comment]
Future readers, this SOF answer might help.

https://stackoverflow.com/questions/30215324/vstest-code-coverage-report-in-jenkins/60219387#60219387

a few bread crumbs

"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe" analyze -output:./TestResults/coverage.xml ./TestResults/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.coverage"

"ReportGenerator_4.4.7\net47\ReportGenerator.exe" -reports:./TestResults/gtest-coverage.xml -targetdir:./TestResults -reporttypes:cobertura

now you have a cobertura.xml file you can digest

**Comment by hisuwh** [comment]
For anyone else who ends up here, this is what worked for me:

```yml
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    resultsFolder: '$(build.ArtifactStagingDirectory)/Test/Results'
    otherConsoleOptions: '/collect:"Code Coverage;Format=Cobertura"'  # <<<< this is the important bit
    codeCoverageEnabled: True

# vv Then add publish coverage manually vv
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(build.ArtifactStagingDirectory)/Test/Results/**/*.xml'
```
