### ISSUE TITLE
VSTest task with code covereage enabled fills up disk with IntelliTrace files

### ISSUE THREAD

**Issue by ChristopherHaws** [Microsoft/vsts-tasks#6694]
## Environment
- Server - VSTS (I can email you account/build details if need be, but I cant post it on a public forum)
- Agent - Private
    - OS: Windows Server 2016 (10.0.14393)
    - Agent Version: 2.129.0

## Issue Description
When using the VSTest Task with CodeCoverage enabled, IntelliTrace logs get placed into the `%WINDIR%\temp\` directory and do not get cleaned up. Our `C:\Windows\Temp` directory was using over 100GB due to `.itrace` files. During the build I was able to locate a file in `F:\vsts\builds\a1\_temp` called `IntelliTrace_Logging_History_15.0_intellitrace_00002bb0_01d3bb24c81e8e1d` with the following content:

```xml
<LoggerInfo xmlns="urn:schemas-microsoft-com:visualstudio:tracelog" name="intellitrace_00002bb0_01d3bb24c81e8e1d" logPath="C:\Windows\Temp\testhost.x86_00002bb0_180313_234117.iTrace" processId="5556" creationTime="0" sessionId="0" keepAlive="false" collectionPlanPath="">
  <ClientInfo id="0" creationTime="0" sessionId="0" name="" processBitness="0" clrVersionMajor="0" commandLine="" />
</LoggerInfo>
```

Here is the yaml of our VSTest task, and we have no custom build variables:
```yaml
steps:
- task: VSTest@2
  inputs:
    testAssemblyVer2: '**\MyProject.Tests.dll'
    vsTestVersion: 15.0
    runInParallel: true
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    rerunFailedTests: false
```

### Error logs
There are no errors occurring other than disk full errors when the disk runs out of space.

## References
DevCommunity post of this issue: https://developercommunity.visualstudio.com/content/problem/195034/cwindowstemp-fills-up-with-itrace-files-after-upgr.html
