### ISSUE TITLE
DownloadBuildArtifacts directly to a folder (without the artifact name)

### ISSUE THREAD

**Issue by eerhardt** [Microsoft/vsts-tasks#6739]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
VSTS
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
devdiv.visualstudio.com

- Agent - Hosted or Private: 
All

    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

`DownloadBuildArtifacts` should allow the artifacts to be downloaded to `downloadPath` without the `artifactName` in the path.

I have:

```
  - task: DownloadBuildArtifacts@0
    displayName: Download package assets
    inputs:
      artifactName: PackageAssets
      downloadPath: $(Build.SourcesDirectory)/bin/obj/packages
```

I expect all the contents of the assets to be directly in the `$(Build.SourcesDirectory)/bin/obj/packages` folder.

However, the contents are under `$(Build.SourcesDirectory)/bin/obj/packages/PackageAssets`

So to workaround this, I need to move the files from `$(Build.SourcesDirectory)/bin/obj/packages/PackageAssets` to `$(Build.SourcesDirectory)/bin/obj/packages` manually.

`DownloadBuildArtifacts` should just allow the contents to be placed in the folder directly.

### Error logs

https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1495163&_a=summary

**Comment by GitHubSriramB** [comment]
@eerhardt - thanks for the feedback. 

Agree that this would be useful enhancement to the task when a Specific Artifact to be downloaded is chosen.  We will add it to our backlog.

**Comment by RoopeshNair** [comment]
@GitHubSriramB - what if multiple artifacts are present? are we considering overwriting common files? IMO, @eerhardt isn't this a corner case?

**Comment by eerhardt** [comment]
I don't think this is a corner case. I think multiple artifacts and having conflicting files in your build is a corner case.  When would having the different phases of your build output the same file be common?

In my scenario, I have multiple "legs"/phases of my build in order to build native assets:

- Windows builds files in `win-x64/mynativelib.dll`
- Linux builds files in `linux-x64/mynativelib.so`
- macOS builds files in `osx-x64/mynativelib.dylib`.

Each leg puts their output in the same artifact, named "PackageAssets". The folder names `win-x64`, `linux-x64`, and `osx-x64` are all preserved under the `PackageAssets` artifact.

Then after all those legs are done, I have a `Package` phase that consumes those native assets and puts them in a NuGet package.  Since they are all in the same artifact `PackageAssets`, I just need to download a single artifact that contains multiple files (in different folders) from the multiple upstream phases:

```
  # Download all agent packages from all previous phases
  - task: DownloadBuildArtifacts@0
    displayName: Download package assets
    inputs:
      artifactName: PackageAssets
      downloadPath: $(Build.SourcesDirectory)/bin/obj/packages
```

The issue is this download call doesn't put the files in the directory I told it to.  I explicitly said, download the assets into `$(Build.SourcesDirectory)/bin/obj/packages`, but it puts my files in `$(Build.SourcesDirectory)/bin/obj/packages/PackageAssets`.  Then I need to move these assets in the next step, to actually put them in the place I intended to put them in the first place.:

```
  # Workaround https://github.com/Microsoft/vsts-tasks/issues/6739
  - task: CopyFiles@2
    displayName: Copy package assets to correct folder
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/bin/obj/packages/PackageAssets
      targetFolder: $(Build.SourcesDirectory)/bin/obj/packages
```

All I'm asking for is a boolean option on DownloadBuildArtifacts that downloads the files to the actual `downloadPath` I specified.  The default can stay the same - to download the files into a folder with the same name as the artifact.  I can opt-in to setting this option to `true`, if I don't want the artifact name in the download path.

If this option is set to true and if multiple artifacts are present and there are common files, raise an error. 
 The user can then deal with it if they want to opt into this behavior and have conflicting files.

**Comment by michael-golfi** [comment]
I'm running into the same issue. Any progress?

As an alternate route I had been thinking of having a itemPattern to match on what to put into the target directory eg:

```
  - task: DownloadBuildArtifacts@0
    displayName: Restore
    inputs:
      artifactName: assets
      targetPattern: assets/**
      downloadPath: $(Build.SourcesDirectory)
```

Then that `**` would specify to put all the subdirectories and files into the downloadPath.
