### ISSUE TITLE
XamariniOS fails to build on my mac as private agent while building from VS directly is fine

### ISSUE THREAD

**Issue by FrancoisM** [Microsoft/vsts-tasks#6844]
On VSTS, after I added the aspnet core Signalr preview nuget package, I got an error about not being able to AOT an assembly.

My build definition runs on my mac which I've setup as a private agent. I use the XamariniOS vsts task.
What I don't understand is that when I build (in Release | iPhone) on my pc connected to my mac it builds fine without the error. 

How come?

**Comment by yacaovsnc** [comment]
Could you please share your build log with `system.debug` set to true?  What is the error you are getting?

**Comment by FrancoisM** [comment]
Here is the error

`MTOUCH : error MT3001: Could not AOT the assembly '/Users/francois/myagent/_work/2/s/Platforms/MyApp.iOS/obj/iPhone/Release/mtouch-cache/Build/Microsoft.AspNetCore.Sockets.Abstractions.dll'`

I'm already on `system.debug` true.

**Comment by bryanmacfarlane** [comment]
The build log should never have secrets and passwords in it.  If it does, it indicates a much more serious problem.  The definition should use variables marked as secret on the definition, service endpoints and/or secured files.  If those are used properly, the get registered as secrets and the agent masks them from the logs.

**Comment by FrancoisM** [comment]
I totally agree with you. My secrets comes from Azure Keyvault and are displayed plain in the log! I had not paid attention before as I didn't have to go through the logs.
Take that task for example:

```
- task: AzureKeyVault@1
    displayName: Getting secrets from Key Vault
    inputs:
        azureSubscription: 'xxxxxxxxxxxxxxxxxxx'
        KeyVaultName: mykeyvault
        SecretsFilter: adminLoginPassword,tokenSecret
```

then later I use the variable `"call az group deployment create.... tokenSecret="$(tokenSecret)"` and I'm surprised to see my token in plain the log!

However, that's another topic. Surely I do something wrong.
