### ISSUE TITLE
Kubeconfig "token" field incorrectly limited to 300 characters

### ISSUE THREAD

**Issue by ajhall** [Microsoft/vsts-tasks#6894]
## Environment
**Server:** VSTS

## Issue Description

This isn't an issue with the VSTS Kubernetes task itself, but with the Kubernetes endpoint definition, which I can't find available on GitHub.

I want to connect to my Kubernetes cluster with a kubeconfig file that uses a JWT (associated with a service account) for authentication. I create a new Kubernetes connection, specify a name and URL, and paste in a kubeconfig that looks similar to this:

```yaml
apiVersion: v1
kind: Config

users:
- name: vsts-deploy
  user:
    token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc-cccccccccccccc-ccccc

clusters:
- cluster:
    server: https://foo.bar.com
    certificate-authority-data: REDACTED
  name: default-cluster

contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: default
    user: vsts-deploy

current-context: default-context
```
When I click OK, an error message appears.

**TFS.WebApi.Exception: The String length exceeds maximum limit. Parameter name: endpoint.Authorization.Parameters[apitoken]**

I can use the same kubeconfig to connect to my cluster via kubectl, so Kubernetes itself appears to be fine with 300+ characters. I think it's just VSTS that's applying the limit.
