### ISSUE TITLE
AzureResourceGroupDeployment@2 deploymentOutputs format

### ISSUE THREAD

**Issue by AlexRamey** [Microsoft/vsts-tasks#6988]
## Environment
- Server - VSTS  
- Agent - Hosted Linux Preview

## Issue Description

The output JSON does not have quotes around it, so tools like jq and powershell ConvertFrom-Json do not work for parsing it.

```yml
...
inputs:
  deploymentOutputs: templateOutput
...
```

Then later in bash script with args: $(templateOutput):
echo $1

yields a JSON string with no quotes

**Comment by AlexRamey** [comment]
No worries. For others, a temporary workaround is to correctly format the output as JSON like so, then proceed as normal (may require updates based on what characters are in play):

```bash
declare -r OUTPUTS=$(echo $1 | sed -r 's/([A-Za-z0-9=-]+)/"\1"/g')
```

**Comment by ds-ms** [comment]
@AlexRamey 
The stringified JSON is updated to the variable name you supply, in your case `$(templateOutput)`. If you want to use it against ConvertFrom-Json, simply enclose the templateOutput in single quotes.
In your case, `ConvertFrom-Json '$(templateOutput)'`

Say for example, your templateOutput's value is stringified version of this object: `{"key":"value"}` 
When you're feeding it as a string to powershell, "key" and "value" are treated as different literals but not as a part of the same string, when you don't enclose them in quotes.

![image](https://user-images.githubusercontent.com/25762922/39693242-03b403b2-5201-11e8-85d9-444814974d4a.png)

**Comment by AlexRamey** [comment]
@ds-ms Thanks for the response. I've verified that you are correct.

Running 
```yaml
- script: echo '$(templateOutput)'
  displayName: Test
```
right after the template deployment prints out the quotes correctly.

However, this does not preserve the quotes:
```yaml
- task: ShellScript@2
  displayName: Parse Template Ouput into Environment Variables
  inputs:
    scriptPath: infrastructure/parse-output.sh
    args: '$(templateOutput)'
```

inside the script
```bash
echo $1
```
