### ISSUE TITLE
task.setvariable only works from powershell?

### ISSUE THREAD

**Issue by joseph-cloudthing** [Microsoft/vsts-tasks#7001]
## Troubleshooting
```
Write-Host "##vso[task.setvariable variable=testvar;]testvalue"
```
only seems to work when I call it from a powershell task on a windows host?

If I `echo` the string instead from a shell script, ([using these examples](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/_shared/set-variables-in-scripts?view=vsts&tabs=shell)) the variables don't set.

I've tried different task types within bash on Linux including the default command & shell tasks, preview (inline scripts) etc. fail.

In each case, later tasks don't see the new value of the variable.

## Environment
- Server - VSTS
- Agent - Private:
    - Ubuntu 16.04, Agent 2.126.0

**Comment by ericsciple** [comment]
This works for me:

```yaml
queue: Hosted Linux Preview
steps:
- script: echo "##vso[task.setvariable variable=foo]asdf"
- script: printenv | sort
```
