### ISSUE TITLE
UsePythonVersion task isn't found in YAML definition

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vsts-tasks#7043]
## Issue Description

I've created a task definition to build a project which specifically requires Python 2.7.  I'm trying to use the [UsePythonVersion](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/UsePythonVersion) task but it results in an error stating that the `UsePythonVersion` task doesn't exist.

```
resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '>= 6.x'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'

- script: |
   script\build.cmd
```

### Error logs

Here's the validation error I get when I try to run the build with this definition:

```
    Phase : Step references task 'UsePythonVersion' at version '0' which does not exist.
```

/cc @brcrista
