### ISSUE TITLE
Directory 'D:\a\1\a' is empty. Nothing will be added to build artifact 'drop'.

### ISSUE THREAD

**Issue by AtwindYu** [Microsoft/vsts-tasks#7247]
- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:Hosted VS2017

## Issue Description

I import my project [https://github.com/RiseSoho/RiseUnity] to vsts and CI it . 
![image](https://user-images.githubusercontent.com/12068896/40228015-b08ddf26-5ac2-11e8-9dfa-3b72959e9bf4.png)

### Error logs

2018-05-18T09:38:47.8669682Z ##[section]Starting: Publish Artifact
2018-05-18T09:38:47.8672893Z ==============================================================================
2018-05-18T09:38:47.8673095Z Task         : Publish Build Artifacts
2018-05-18T09:38:47.8673247Z Description  : Publish build artifacts to Visual Studio Team Services/TFS or a file share
2018-05-18T09:38:47.8673365Z Version      : 1.133.0
2018-05-18T09:38:47.8673466Z Author       : Microsoft Corporation
2018-05-18T09:38:47.8673817Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=708390)
2018-05-18T09:38:47.8673977Z ==============================================================================
2018-05-18T09:38:48.1337734Z ##[warning]Directory 'D:\a\1\a' is empty. Nothing will be added to build artifact 'drop'.
2018-05-18T09:38:48.1355716Z ##[section]Finishing: Publish Artifact

**Comment by JohannesDrexler** [comment]
You don't copy anything to $(build.artifactstagingdirectory) in your definition. You are missing a 'Copy Files'-Task before the 'publish artifact'

**Comment by bryanmacfarlane** [comment]
@JohannesDrexler is correct.  You can also avoid the copy and pass a directory to publish other than the artifacts directory.  Note that copy takes all the mini match patterns and publish just take a directory.

**Comment by sshrishi** [comment]
I am having same issue. I tried all the above options but stuck on this one.
Fresher Joe :- Was this resolved for you?

**Comment by molikmiah** [comment]
@sshrishi did you manage to resolve the issue?

**Comment by sshrishi** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Fisher-Joe** [comment]
@sshrishi , Yes, It's resolved for me.

**Comment by SuperDuperOne** [comment]
can we get information on how you resolved this issue as I've hit the same wall.
thanks!
@sshrishi and @Fisher-Joe

**Comment by sshrishi** [comment]
> can we get information on how you resolved this issue as I've hit the same wall.
> thanks!
> @sshrishi and @Fisher-Joe

Do you still have issue?

**Comment by benwinston** [comment]
@SuperDuperOne For more information on the Copy Files Task, take a look at: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml. Specifically for my setup running Ubuntu 18.04, the following block was implemented before Publish in `azure_pipelines.yaml`:

`- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    targetFolder: $(Build.ArtifactStagingDirectory)`

**Comment by bz-wow** [comment]
I tried a .net core app, encountered the issue as well. But it doesn't need a copy file task, instead we can specify an output location for the "dotnet build" command, to let it output to $(Build.ArtifactStagingDirectory). Samples as below.

`steps:
- script: dotnet build --configuration $(buildConfiguration) **--output $(Build.ArtifactStagingDirectory)**
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'`

**Comment by rohans03** [comment]
> @Fisher-Joe Can you help me, how you resolved this issue as I am facing same thing

**Comment by jhgdenver** [comment]
I was able to resolve this issue by building to the Artifact Staging Directory:

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    **msbuildArgs: '/p:OutputPath=$(Build.ArtifactStagingDirectory)'**
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'MyServiceName'

**Comment by jhgdenver** [comment]
I was able to resolve this by building to the Artifact Staging Directory:

```

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:OutputPath=$(Build.ArtifactStagingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'MyServiceName'
```
