### ISSUE TITLE
Can not pull docker image from Docker Hub

### ISSUE THREAD

**Issue by Davis10733** [Microsoft/vsts-tasks#7298]
## Environment
VSTS - Linux Hosted Agent

## Issue Description
I try to create Redis container during CI process, but it fails and show up `Failed which: Not found docker: null`. It used to work, is anything change in the latest deployment ?

vsts.ci.yml
```
queue: Hosted Linux Preview
variables:
  _PREVIEW_VSTS_DOCKER_IMAGE: "jermysu/docker-vsts-ci:0.10"

steps:
- task: Docker@0
  displayName: create redis service
  inputs:
    imageName: "redis:4.0.9"
    action: "Run an image"
    containerName: "client-server-redis_1"

```
### Error logs

2018-05-25T03:42:08.6993925Z ##[debug]loaded 24
2018-05-25T03:42:08.7040514Z ##[debug]check path : /_work/_tasks/Docker_e28912f1-0114-4464-802a-a3a35437fd16/0.3.12/task.json
2018-05-25T03:42:08.7088335Z ##[debug]set resource file to: /_work/_tasks/Docker_e28912f1-0114-4464-802a-a3a35437fd16/0.3.12/task.json
2018-05-25T03:42:08.7133780Z ##[debug]system.culture=en-US
2018-05-25T03:42:08.7178766Z ##[debug]cwd=/_work/1/s
2018-05-25T03:42:08.7227148Z ##[debug]containerregistrytype=Azure Container Registry
2018-05-25T03:42:08.7272004Z ##[debug]azureSubscriptionEndpoint=null
2018-05-25T03:42:08.7316810Z ##[debug]azureContainerRegistry=null
2018-05-25T03:42:08.7360850Z ##[debug]check path : null
2018-05-25T03:42:08.7405656Z ##[debug]task result: Failed
2018-05-25T03:42:08.7529529Z ##[error]Unhandled: Failed which: Not found docker: null
2018-05-25T03:42:08.7592861Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Failed which: Not found docker: null
2018-05-25T03:42:08.7672293Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Failed which: Not found docker: null
2018-05-25T03:42:08.7717949Z ##[debug]Handler exit code: 0
2018-05-25T03:42:08.7781849Z ##[section]Finishing: create redis service
