### ISSUE TITLE
Docker Compose task in VSTS : Couldn't connect to Docker daemon at http+docker://localhost - is it running?

### ISSUE THREAD

**Issue by chetanku** [Microsoft/vsts-tasks#7360]
Installed docker 18.03 on vsts agent box(on premises VSTS agent) The user under which the agent is running has been added to the docker group. When I try to build using Docker Compose task in VSTS, the build fails with error:

**Couldn't connect to Docker daemon at http+docker://localhost - is it running?
 If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable. 
Couldn't connect to Docker daemon at http+docker://localhost - is it running? 
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable. /usr/local/bin/docker-compose failed with return code: 1**

**ERROR Image**

![image](https://user-images.githubusercontent.com/10711779/40878901-f148b032-6665-11e8-816d-105cbd5fd1c4.png)

I have been stuck in this for few days, any help will be awesome.

One more note: docker compose works perfectly fine from the agent box, but when the build is triggered by VSTS task I get this error.

**TASK** 

![image](https://user-images.githubusercontent.com/10711779/40878886-ac04de56-6665-11e8-8c03-5ed0b660f657.png)

**docker-compose file:**

 ```
version: '3'
services:
  some-api:
    build:
      context: .
      dockerfile: .docker/dockerfile1
    image: some.azurecr.io/some-api:latest     
    container_name: 'some-api'
    ports:
        - '8080:80'
  some-website:
    build: 
      context: .
      dockerfile: .docker/dockerfile2
    image: some.azurecr.io/some-website:latest
    container_name: 'some-website'
    ports:
        - '3434:3434'
```
**dockerfile -api**

```
FROM microsoft/dotnet AS build 
# Docker image container .NET Core SDK

COPY .api/ ./some-api

WORKDIR /some-api

RUN dotnet restore; dotnet publish -o out


# final image

FROM microsoft/aspnetcore 
# .NET Core runtime-only image

COPY --from=build /some-api/out /some-api

WORKDIR /some-api

EXPOSE 80

ENTRYPOINT [ "dotnet", "some.dll" ]

```
**dockerfile-website**
```
#----------------------
### STAGE 1: BUILD ###
#---------------------


# Building node from LTS version
FROM node:8.11.1 as builder

# Installing npm to remove warnings and  optimize the container build process
# One of many warnings: npm WARN notice [SECURITY] deep-extend has 1 low vulnerability. 
#Go here for more details: https://nodesecurity.io/advisories?search=deep-extend&version=0.5.0 - 
#Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

RUN npm install npm@latest -g

# Copying all necessary files required for npm install

COPY package.json ./

# Install npm dependencies in a different folder to optimize container build process

RUN npm install

# Create application directory and copy node modules to it

RUN mkdir /some-website
RUN cp -R ./node_modules ./some-website

# Setting application directory as work directory
WORKDIR /some-website

# Copying application code to container application directory
COPY . .

# Building the angular app
RUN npm run build.prod

#--------------------------------------------------
### STAGE 2: Setup nginx and Deploy application ###
#--------------------------------------------------
FROM nginx:latest

## Copy defualt ngninx configuration file

COPY default.conf /etc/nginx/conf.d

## Remove default nginx website

RUN rm -rf /usr/share/nginx/hmtl/*

# Copy dist folder from  the builder to nginx public folder(STAGE 1)

COPY --from=builder /some-website/dist/prod /usr/share/nginx/html

CMD ["nginx","-g","daemon off;"]
```
Thanks
