### ISSUE TITLE
Azure CLI task strips % from input

### ISSUE THREAD

**Issue by riezebosch** [Microsoft/vsts-tasks#8104]
```yaml
resources:
- repo: self
  
queue:
  name: Hosted VS2017

steps:
- task: AzureCLI@1
  inputs:
    azureSubscription: My Subscription
    scriptLocation: inlineScript
    inlineScript: 'echo single percent sign % and double percent sign %%'
```

Output:
```
2018-08-22T11:08:05.4378344Z D:\a\1\s>echo single percent sign  
2018-08-22T11:08:05.4380845Z single percent sign 
```
