### ISSUE TITLE
Run `xcodebuild` from ShellScript task?

### ISSUE THREAD

**Issue by nick-thompson** [Microsoft/vsts-tasks#8354]
## Issue Description
I have a bash script in my project root that prepares my build artifacts with a call to `xcodebuild`, followed by moving some files around and `pkgbuild` commands. When run locally, this works great. When run on the hosted macOS agent, my `xcodebuild` fails immediately. Is it possible to run `xcodebuild` in this way on the hosted macOS agent? My config file is as follows:

```
jobs:
- job: OSX
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: sleep 15
  - task: ShellScript@2
    inputs:
      scriptPath: ./scripts/run.sh
      args: build wov
```
Note– the `sleep 15` was a sort of last ditch attempt after reading various blogs that suggested that the vm environment was not all the way setup by the time `xcodebuild` was running. It didn't work :)

### Task logs

[log_13_6.zip](https://github.com/Microsoft/vsts-tasks/files/2397097/log_13_6.zip)

### Error logs

```
2018-09-19T12:44:48.8872400Z ##[error]/bin/bash failed with return code: 65
2018-09-19T12:44:48.8974600Z ##[error]Bash failed with error: /bin/bash failed with return code: 65
```
