### ISSUE TITLE
Adding repos with Helm Deploy task

### ISSUE THREAD

**Issue by timwebster9** [Microsoft/vsts-tasks#8374]
I would like to install Open Service Broker for Azure on my AKS cluster.  I need to do stuff like this:

```
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
helm install svc-cat/catalog --name catalog --namespace catalog \
   --set apiserver.storage.etcd.persistence.enabled=true
```

However there is no `repo` option for the Helm task.  How would I go about doing the above with VSTS tasks?

EDIT: I'm using Azure DevOps

**Comment by timwebster9** [comment]
nevermind - it works if you use `repo` for the task and pass the rest of it in the `arguments` argument.  Perhaps the docs need to be updated?  Currently it says:

```
#command: 'ls' # Options: create, delete, expose, get, init, install, login, logout, ls, package, rollback, upgrade
```

**Comment by vithati** [comment]
@timwebster9 , I have opened workitem internally to track for adding more information in task document.

**Comment by michaelmcneil-corgi** [comment]
I have this same issue, but there is no `repo` command available for this task?

**Comment by timwebster9** [comment]
@michaelmcneil-corgi 

if you're using YAML, this is what we're doing:

```
steps:
- task: HelmDeploy@0
  displayName: 'Add Service Catalog Helm Repo'
  enabled: true
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: ${{ parameters.serviceConnection }}
    azureResourceGroup: ${{ parameters.aksResourceGroup }}
    kubernetesCluster: ${{ parameters.aksClusterName }}
    command: 'repo'
    arguments: 'add svc-cat https://svc-catalog-charts.storage.googleapis.com'
```
