### ISSUE TITLE
Python task fails if inline script contains if, while, etc... statements. "Mapping values are not allowed in this context."

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/vsts-tasks#8390]
## Environment
- Server - Azure DevOps Pipeline
    
  - If using VSTS, provide the account name, team project name, build definition name/build number:
    - Account: dekeeler.visualstudio.com
    - Team Project Name: Python-VSCode
    - Build Definition Name: vscode-python-linux-unit-CI
    - Build Number: 275    

- Agent - Hosted
    - Agent Pool Name: Hosted Ubuntu 1604

## Issue Description

If I create a YAML based pipeline, add a python script task, and add the following code to my script:

```python
      import os
      import os.path
      
      mocha_reportfile = os.environ.get('MOCHA_CI_REPORTFILE')
      
      if not os.path.exists(mocha_reportfile):
          print("##vso[task.logissue type=error;]No test report file was found at {}.".format(mocha_reportfile))
```

I get an error immediately after queueing my build:

---
Progression

Build pipeline failed
1 Error(s) / 0 Warning(s)

  :x: unittest-template.yml (Line: 152, Col: 48, Idx: 3653) - (Line: 152, Col: 48, Idx: 3653): Mapping values are not allowed in this context.

---

It would seem that the YAML parser doesn't like my if statement:

```python
      if not os.path.exists(mocha_reportfile): # <= This seems to be triggering a mapping attempt.
```

### Task logs

*No logs are available, the build terminates before any downloadable log is available.*

### Error logs

*No error logs available either, other than what I've posted above.*

> Edit: Update agent pool name (instead of queue name).

**Comment by d3r3kk** [comment]
Here's the snippet from my YAML file:

```yaml

  - task: PythonScript@0
    displayName: 'Run a Python script'
    inputs:
      scriptSource: inline
      script: |
      import os
      import os.path
      
      mocha_reportfile = os.environ.get('MOCHA_CI_REPORTFILE')
      
      if not os.path.exists(mocha_reportfile):
          print("##vso[task.logissue type=error;]No test report file was found at {}.".format(mocha_reportfile))
```

**Comment by d3r3kk** [comment]
aaaaaand... the tabs fixed the issue. Saw it immediately in markdown but was blind to it in VSCode for some reason.

```yaml
  - task: PythonScript@0
    displayName: 'Run a Python script'
    inputs:
      scriptSource: inline
      # indentation matters in the script part...
      script: |
        import os
        import os.path
      
        mocha_reportfile = os.environ.get('MOCHA_CI_REPORTFILE')
      
        if not os.path.exists(mocha_reportfile):
            print("##vso[task.logissue type=error;]No test report file was found at {}.".format(mocha_reportfile))
```

I am going to set my tab size to 4 for YAML, and go to bed now. So sorry for the noise.

Keep up the excellent work folks.
